### ISSUE TITLE
There is no compiler in the .zip (option 1)

### ISSUE THREAD

**Issue by PhilippeChab** [CromFr/STNeverwinterScript#1]
If I look at the package settings: 
`"compiler_cmd": ["C:\\Program Files (x86)\\NWNScriptCompiler\\NWNScriptCompiler.exe"],`

But there is no compiler in the .zip downloaded if you use option 1. It is only the repo files.

Not sure if I'm missing something or this option just never worked.

Your package is awesome by the way!

**Comment by PhilippeChab** [comment]
I finally made it work. 

I think you should just specifiy in the readme that you need to change the paths in the package settings to point on a nwn compiler and nwnscript.nss.

But the option 1 is definitively broken.

**Comment by CromFr** [comment]
Hi !
Sorry for the late reply, I definitely need to pay more attention to my github notifications :/ 

I updated the readme to provide the direct link for the compiler zip file (you had to download the zip file named "NWNScriptCompiler.zip") and changed the sublime settings to add links to the compiler setup instructions.
